"use client";
import { Activity, ArrowRight, CheckCircle2, Clock3, ShieldCheck } from "lucide-react";
import { useTranslation } from "@/components/layout/language-provider";
import { fmt, isotopeLabel, isotopes } from "@/lib/metrology";
import { Panel, Status, type WorkspaceProps } from "./shared";
import { LongTermCharts } from "./results-station";
import { AnchorPair, MethodFacts, UncertaintySummary } from "./qualification-summary";
import { WorkflowStart } from "./workflow-start";

export function MetrologyOverview(props:WorkspaceProps & {navigate:(section:string)=>void;openRun:(id:string)=>void;openSession:(id:string)=>void}) {
  const tr=useTranslation();const {state}=props;const method=state.active_method;
  const due=state.next_review?new Date(state.next_review):null;
  const days=due?Math.ceil((due.getTime()-Date.now())/86400000):null;
  const interval=method?.config.qualification_interval_days??60;
  const elapsed=days==null?0:Math.min(100,Math.max(0,100*(interval-days)/interval));
  const populations=state.history.filter(h=>h.method_id===method?.id&&(!state.operational||h.data_origin==="synthetic"));
  const waiting=(state.results_sessions??[]).filter(s=>["awaiting_review","blocked","open"].includes(s.status));
  return <div className="metro-stack">
    <div className="station-overview-grid"><section className="station-qualification-board"><div className="station-board-title"><span><ShieldCheck size={18}/>{tr("Current qualification")}</span><Status value={state.status}/></div><h2>{method?.config.name??tr("Qualification needed")}</h2><p>{method?`${tr("Validated method")} v${method.version} · ${method.config.instrument}`:tr("Define the method and review a carousel before processing routine results.")}</p><MethodFacts method={method} compact/><div className="station-qualified-pair"><div><small>{tr("Latest approved assessment")}</small><strong>{method?.approval?.at?.slice(0,10)??"—"}</strong></div><div><small>{tr("Next metrological review")}</small><strong>{state.next_review?.slice(0,10)??"—"}</strong></div></div><div className="station-qualification-horizon" aria-label={tr("Periodic qualification interval")}><span style={{width:`${elapsed}%`}}/><i style={{left:`${elapsed}%`}}/></div><div className="station-horizon-labels"><span>{tr("Qualified")}</span><b>{days==null?tr("Review interval not set"):days<0?`${Math.abs(days)} ${tr("days overdue")}`:`${days} ${tr("days until review")}`}</b><span>{interval} {tr("days")}</span></div><div className="metro-actions"><button className="metro-btn primary" onClick={()=>props.navigate("qualification")}><ShieldCheck size={14}/>{tr("Update qualification")}</button><button className="metro-btn" onClick={()=>props.navigate("results?new=1")}>{tr("New results session")}<ArrowRight size={14}/></button></div></section>
      <section className="station-acceptance-board"><h2>{tr("Acceptance criteria")}</h2><table><thead><tr><th>{tr("QC criterion")}</th>{isotopes.map(i=><th key={i}>{isotopeLabel[i]}</th>)}</tr></thead><tbody>{(["external_sd","internal_sd","bias"] as const).map(key=><tr key={key}><td>{tr({external_sd:"Run QC SD",internal_sd:"Internal analysis SD",bias:"Absolute mean bias"}[key])}</td>{isotopes.map(i=><td key={i}>{key==="bias"?"≤":"<"} {fmt(method?.config.qc[key][i],2)}<small> ‰</small></td>)}</tr>)}</tbody></table><div className="station-qc-frequency"><Activity size={17}/><span><b>SHP2L</b><small>{tr("Independent QC every")} {method?.config.qc.max_unknowns_between_qc??4} {tr("unknowns")}</small></span></div><p>{method?`${method.config.ranges.mass_ug?.low}–${method.config.ranges.mass_ug?.high} µg · ${method.config.ranges.i44_v?.low}–${method.config.ranges.i44_v?.high} V`:tr("Operating ranges await validation")}</p></section><section className="station-uncertainty-board metro-panel"><h2>{tr("Uncertainty / ‰")}</h2><UncertaintySummary method={method}/><p className="metro-muted">{tr("u_prec is individual QC SD; u_norm and u_corr vary with each result.")}</p></section></div>
    <div className="station-status-band"><div><CheckCircle2 size={18}/><span>{tr("Dual-point anchors")}<b>{method?.config.anchor_ids.map(id=>state.materials.find(m=>m.id===id)?.name).join(" + ")||"NBS18 + NBS19"}</b></span></div><div><Activity size={18}/><span>{tr("Current QC population")}<b>{populations.reduce((n,h)=>n+h.isotopes.d13c.n,0)} {tr("individual observations")}</b></span></div><div><Clock3 size={18}/><span>{tr("Sessions awaiting review")}<b>{waiting.length} {tr("sessions")}</b></span></div><div><ShieldCheck size={18}/><span>{tr("Routine normalization")}<b>{tr(method?"Retained from Qtegra":"Pending qualification")}</b></span></div></div>
    <div className="station-overview-evidence"><AnchorPair method={method}/><LongTermCharts state={state} openRun={props.openRun}/></div>
    <WorkflowStart {...props}/>
    {state.operational&&<Panel title={tr("Operational laboratory simulation")}><div className="station-source-register">{state.operational.sessions.map(s=><button key={s.id} onClick={()=>props.openSession(s.id)}><span>{s.client}</span><strong>{s.project}</strong><small>{s.run_count} {tr("raw workbooks")} · {s.unique_analyses} {tr("analyses")}</small><ArrowRight size={18}/></button>)}</div><p className="metro-muted">{state.operational.counts.observed_qc} {tr("observed QC aliquots")} · {tr("Historical exports retain their original dates. Mock calibration is a comparison model, not verified historical transfer.")}</p></Panel>}

    <Panel title={tr("Recent results sessions")}><div className="metro-table-wrap"><table><thead><tr><th>{tr("Client")}</th><th>{tr("Session")}</th><th>{tr("Analyses")}</th><th>{tr("Status")}</th><th/></tr></thead><tbody>{[...(state.results_sessions??[])].reverse().slice(0,7).map(s=><tr key={s.id}><td>{s.client}</td><td><b>{s.name}</b><small className="station-cell-subtitle">{s.project} · {s.acquired_date??s.created_at.slice(0,10)}</small></td><td>{s.analysis_count}</td><td><Status value={s.status}/></td><td><button className="metro-btn" onClick={()=>props.openSession(s.id)}>{tr("Open session")}<ArrowRight size={13}/></button></td></tr>)}</tbody></table></div></Panel>
  </div>;
}
