"use client";

import { useTranslation } from "@/components/layout/language-provider";
import { useEffect, useState } from "react";
import { ResultsStation } from "./results-station";
import { METROLOGY_API, fmt, human, isotopeLabel, isotopes, metroRequest, type Diagnostics, type Fit, type RunDetail } from "@/lib/metrology";
import { RowReview } from "./row-review";
import { BusyButton, Empty, Field, Inspect, Panel, Scatter, Status, type WorkspaceProps } from "./shared";

export function Runs(props: WorkspaceProps & { initialRunId?: string }) {
  const tr = useTranslation();
  const [id, setId] = useState(props.initialRunId || props.state.runs.at(-1)?.id || "");
  const [detail, setDetail] = useState<RunDetail | null>(null);
  const [error, setError] = useState("");
  const selected = props.state.runs.find(r => r.id === id) ?? props.state.runs.at(-1);
  useEffect(() => {
    if (!selected) return;
    const controller = new AbortController();
    setError("");
    metroRequest<RunDetail>(`/runs/${selected.id}`, { signal: controller.signal }).then(setDetail).catch(e => { if (!controller.signal.aborted) setError(e.message); });
    return () => controller.abort();
  }, [selected, props.state]);
  useEffect(() => { if (props.initialRunId) setId(props.initialRunId); }, [props.initialRunId]);
  useEffect(() => { if (detail?.id === selected?.id) document.querySelector(".metro-station-heading")?.scrollIntoView({ block: "start" }); }, [detail?.id, selected?.id]);
  return <div className="metro-stack">
    <details><summary>{tr("Run register")} / {props.state.runs.length}</summary><Panel title={tr("Analytical runs")}>{props.state.runs.length ? <div className="metro-table-wrap"><table><thead><tr><th>{tr("Run")}</th><th>{tr("Context")}</th><th>{tr("Analyses")}</th><th>{tr("Status")}</th><th>{tr("Review")}</th></tr></thead><tbody>{[...props.state.runs].reverse().map(r => <tr key={r.id}><td>{r.label}<div className="metro-muted">{tr(r.acquired_date || r.created_at.slice(0,10))}</div></td><td>{tr(r.context)}</td><td className="num">{r.analysis_count}</td><td><Status value={r.status} /></td><td><button className="metro-btn" onClick={() => setId(r.id)} aria-pressed={selected?.id === r.id}>{tr("Open run")}</button></td></tr>)}</tbody></table></div> : <Empty>{tr("Import the qualification carousel or a routine Qtegra run.")}</Empty>}</Panel></details>
    {tr(error && <p role="alert" className="metro-note error">{tr(error)}</p>)}{selected && (!detail || detail.id !== selected.id) && <p role="status">{tr("Loading analytical run…")}</p>}{detail && detail.id === selected?.id && <RunReview {...props} key={`${detail.id}-${detail.revision}-${detail.latest_evaluation_id}-${detail.status}`} run={detail} />}
  </div>;
}

export function RunReview({ run, initialTab = "results station", fixedView, includedIds, ...props }: WorkspaceProps & { run: RunDetail; initialTab?: string;fixedView?:boolean;includedIds?:string[] }) {
  const tr = useTranslation();
  const [tab, setTab] = useState(initialTab);
  const [reviewId,setReviewId]=useState("");
  const [problemsOnly,setProblemsOnly]=useState(false);
  const [massText, setMassText] = useState("");
  const [massError, setMassError] = useState("");
  const [excludeId, setExclude] = useState("");
  const [evidence, setEvidence] = useState("");
  const [educational, setEducational] = useState<unknown>(null);
  const [raw, setRaw] = useState<unknown>(null);
  const [localError, setLocalError] = useState("");
  const [methodId, setMethod] = useState(run.method_id ?? props.state.active_method?.id ?? "");
  const evaluation = run.evaluation;
  const rows = (evaluation?.results ?? run.measurements).map(row=>({...row,issues:row.issues?.filter(issue=>!issue.startsWith("mass_ug "))}));
  const diagnostic = evaluation?.diagnostics ?? run.diagnostics;
  const locked = run.status === "released" || props.state.qualifications.find(q => q.id === run.qualification_id)?.status === "approved";
  async function inspect(path: string, setter: (value: unknown) => void) { try { setter(await metroRequest(path)); setLocalError(""); } catch (e) { setLocalError(e instanceof Error ? e.message : "Inspection failed"); } }
  return <Panel title={run.label}><div className="metro-actions" style={{ marginTop: 0 }}><Status value={run.status} /><span className="metro-muted">{run.source.analysis_count}{tr(" analyses · ")}{run.source.cycle_count}{tr(" numbered cycles")}</span><a className="metro-btn" href={`${METROLOGY_API}/sources/${run.raw_import_id}`}>{tr("Download original workbook")}</a></div>
    {run.warnings.length > 0 && <details className="station-import-notes"><summary>{tr("Import notes")} · {run.warnings.length}</summary><ul className="station-issue-list">{run.warnings.map(w=><li key={w}>{tr(w)}</li>)}</ul></details>}
    {["measurements","processing"].includes(tab)&&!locked&&<div className="metro-actions">
      <button className="metro-btn primary" disabled={props.busy||!methodId} onClick={()=>void props.act(`/runs/${run.id}/evaluate`,{method_id:methodId})}>{tr("Evaluate run")}</button>
      {!run.acquisition_complete&&run.warnings.some(w=>w.includes("Running"))&&<button className="metro-btn" disabled={props.busy} title={tr("Verify the acquisition has completed in Qtegra before recording this confirmation. The exported status remains unchanged.")} onClick={async()=>{const saved=await props.act(`/runs/${run.id}/annotations`,{acquisition_complete:true});if(saved)await props.act(`/runs/${run.id}/evaluate`,{method_id:methodId});}}>{tr("Record verified acquisition completion")}</button>}
      {run.context==="routine"&&evaluation&&<button className="metro-btn" disabled={props.busy||!evaluation.ready||run.release_blockers.length>0} onClick={()=>void props.act(`/runs/${run.id}/release`,{evaluation_id:evaluation.id})}>{tr("Review and release results")}</button>}
    </div>}
    {tab==="measurements"&&<div className="metro-actions"><label className="metro-check"><input type="checkbox" checked={problemsOnly} onChange={e=>setProblemsOnly(e.target.checked)}/>{tr("Only analyses requiring review")} ({rows.filter(r=>r.issues?.length&&!r.excluded).length})</label><span className="metro-muted">{tr("Select a highlighted row to review its evidence, annotate missing inputs or record an exception.")}</span></div>}
    {!fixedView && <div className="metro-tabs" role="tablist" aria-label={tr("Run review")} style={{ marginTop: 22 }}>{["results station", "measurements", "diagnostics", "processing", "traceability"].map(t => <button key={t} role="tab" aria-selected={tab === t} onClick={() => setTab(t)}>{tr(human(t))}</button>)}</div>}
    {tab === "results station" && <ResultsStation run={run} state={props.state} />}
    {tab === "measurements" && <div className="metro-stack"><div className="metro-table-wrap"><table><thead><tr><th>{tr("Analysis")}</th><th>{tr("Sample / comment")}</th><th>{tr("Qtegra type")}</th><th>{tr("Mass / µg")}</th><th>{tr("I44 / V")}</th><th>{tr("δ¹³C / ‰")}</th><th>{tr("SD / ‰")}</th><th>{tr("δ¹⁸O / ‰")}</th><th>{tr("SD / ‰")}</th><th>{tr("Review / evidence")}</th></tr></thead><tbody>{rows.filter(r=>!problemsOnly||(r.issues?.length&&!r.excluded)).map(r => <tr key={r.id} className={r.excluded?"station-row-excluded":r.issues?.length?"station-row-problem":r.accepted_issues?.length?"station-row-accepted":""}><td>{tr(r.source_index)}{r.excluded && <Status value="excluded" />}</td><td>{r.label}<div className="metro-muted">{r.comment}</div></td><td>{tr(r.sample_type)}<div className="metro-muted">{tr(human(r.role || r.source_role))}</div></td><td className="num">{tr(fmt(run.masses_ug[r.id] ?? r.mass_ug,1))}</td><td className="num">{tr(fmt(r.i44_v))}</td><td className="num">{tr(fmt(r.d13c))}</td><td className="num">{tr(fmt(r.d13c_sd))}</td><td className="num">{tr(fmt(r.d18o))}</td><td className="num">{tr(fmt(r.d18o_sd))}</td><td><Status value={r.excluded?"excluded":r.issues?.length?"review_required":"pass"}/><button className="metro-btn" aria-expanded={reviewId===r.id} onClick={()=>setReviewId(reviewId===r.id?"":r.id)}>{tr("Review analysis")} {r.issues?.length?`(${r.issues.length})`:""}</button> <button className="metro-btn" onClick={() => void inspect(`/measurements/${r.id}`, setRaw)}>{tr("Raw rows")}</button></td></tr>)}</tbody></table></div>
      {rows.find(r=>r.id===reviewId)&&<RowReview {...props} key={reviewId} row={rows.find(r=>r.id===reviewId)!} run={run}/>}
      {raw != null && <Inspect title={tr("Selected measurement, original rows and cycles")} value={raw} />}
      {!locked && <div className="metro-grid"><form className="metro-stack" onSubmit={async e => { e.preventDefault(); setMassError(""); const masses: Record<string, number> = {}; for (const line of massText.split("\n").filter(l => l.trim())) { const [index, mass] = line.split(",").map(v => v.trim()); const row = rows.find(r => r.source_index === index); if (!row || !mass || !Number.isFinite(Number(mass)) || Number(mass) <= 0) { setMassError(`Invalid analysis index or mass: ${line}`); return; } masses[row.id] = Number(mass); } if (!Object.keys(masses).length) { setMassError("Enter at least one analysis index and mass"); return; } await props.act(`/runs/${run.id}/annotations`, { masses_ug: masses }); }}><h3>{tr("Weighed-mass annotations")}</h3><Field label={tr("Analysis index, mass in µg. One pair per line.")}><textarea value={massText} onChange={e => setMassText(e.target.value)} placeholder={tr("1, 60\n2, 100")} required /></Field><p className="metro-muted">{tr("Annotations are stored separately from the source measurements. Explicit MASS=… ug comments are parsed automatically.")}</p>{tr(massError && <p className="metro-note error" role="alert">{tr(massError)}</p>)}<BusyButton busy={props.busy}>{tr("Save weighed masses")}</BusyButton></form>
      <form className="metro-stack" onSubmit={e => { e.preventDefault(); void props.act(`/runs/${run.id}/exclusions`, { measurement_id: excludeId, evidence }); }}><h3>{tr("Document an analytical exclusion")}</h3><Field label={tr("Measurement")}><select required value={excludeId} onChange={e => setExclude(e.target.value)}><option value="">{tr("Select an analysis")}</option>{rows.filter(r => !run.exclusions.some(x => x.measurement_id === r.id)).map(r => <option key={r.id} value={r.id}>{tr(r.source_index)} · {r.label}</option>)}</select></Field><Field label={tr("Rule or evidence supporting exclusion")}><textarea required minLength={3} value={evidence} onChange={e => setEvidence(e.target.value)} /></Field><p className="metro-muted">{tr("Original values remain stored. Precision is recalculated only after a new evaluation.")}</p><BusyButton busy={props.busy} primary={false}>{tr("Record exclusion")}</BusyButton></form></div>}
    </div>}
    {tab==="measurements"&&evaluation&&<details><summary>{tr("Session-level release criteria")}</summary><ul className="station-issue-list">{[...new Set([...evaluation.blockers,...run.release_blockers])].filter(issue=>!issue.startsWith("Analysis ")).map(issue=><li key={issue}>{tr(issue)}</li>)}</ul></details>}
    {tab === "diagnostics" && (diagnostic ? <DiagnosticView data={diagnostic} /> : <Empty>{tr("Evaluate the run against a method to inspect its diagnostics.")}</Empty>)}
    {tab === "processing" && <div className="metro-stack">{!locked && <form className="metro-form-grid" onSubmit={e => { e.preventDefault(); void props.act(`/runs/${run.id}/evaluate`, { method_id: methodId || null }); }}><Field label={tr("Method version")}><select required disabled={!!run.method_id} value={methodId} onChange={e => setMethod(e.target.value)}><option value="">{tr("Select active method")}</option>{props.state.methods.filter(m => m.id === run.method_id || m.status === "active").map(m => <option key={m.id} value={m.id}>{tr("v")}{m.version} · {tr(m.status)}</option>)}</select></Field><div className="metro-actions"><BusyButton busy={props.busy}>{tr("Evaluate run")}</BusyButton></div></form>}
      {!locked && !run.acquisition_complete && run.warnings.some(w => w.includes("Running")) && <div className="metro-note warn"><p>{tr("Verify the acquisition has completed in Qtegra before recording this confirmation. The exported status remains unchanged.")}</p><button className="metro-btn" disabled={props.busy} onClick={() => void props.act(`/runs/${run.id}/annotations`, { acquisition_complete: true })}>{tr("Record verified acquisition completion")}</button></div>}
      {evaluation ? <><div className="metro-grid">{isotopes.map(iso => { const qc = evaluation.qc.isotopes[iso]; return <section key={iso} className="metro-panel"><h3>{tr(isotopeLabel[iso])}{tr(" independent QC")}</h3><Status value={qc.passed ? "pass" : "fail"} /><dl><div className="metro-meter"><dt>{tr("Individual aliquots")}</dt><dd>{qc.n}</dd></div><div className="metro-meter"><dt>{tr("Mean / ‰ VPDB")}</dt><dd>{tr(fmt(qc.mean))}</dd></div><div className="metro-meter"><dt>{tr("Run-level SD / ‰")}</dt><dd>{tr(fmt(qc.sd))}</dd></div><div className="metro-meter"><dt>{tr("Mean bias / ‰")}</dt><dd>{tr(fmt(qc.bias))}</dd></div></dl></section>; })}</div>
        <p className="metro-muted">{rows.filter(r=>r.issues?.length&&!r.excluded).length} {tr("analyses require review in Import.")}</p>
        <div className="metro-table-wrap"><table><thead><tr><th>{tr("Sample")}</th><th>{tr("Role")}</th><th>{tr("δ¹³C / ‰ VPDB")}</th><th>{tr("U / ‰")}</th><th>{tr("δ¹⁸O / ‰ VPDB")}</th><th>{tr("U / ‰")}</th><th>{tr("Review")}</th></tr></thead><tbody>{rows.filter(r => r.isotopes && Object.keys(r.isotopes).length && (!includedIds || r.role!=="unknown" || includedIds.includes(r.id))).map(r => <tr key={r.id}><td>{tr(r.source_index)} · {r.label}</td><td>{tr(r.role)}</td>{isotopes.map(iso => <td key={iso} colSpan={2}><div style={{ display: "flex", justifyContent: "space-between", gap: 14 }}><span>{tr(fmt(r.isotopes?.[iso]?.value))}</span><span>{tr(fmt(r.isotopes?.[iso]?.budget?.expanded_uncertainty))}</span></div></td>)}<td>{tr(r.issues?.length ? <Status value="review_required" /> : "Within criteria")}</td></tr>)}</tbody></table></div>
        <details><summary>{tr("Educational mode: normalization and uncertainty")}</summary><div className="metro-note" style={{ marginTop: 12 }}>{tr("y = A₁ + (x − M₁) × (A₂ − A₁) / (M₂ − M₁). Assigned values and measured anchor means carry separate uncertainties. The full covariance propagates through this equation. The QC dispersion is an individual-observation SD, not an SE.")}</div>{isotopes.map(iso => <div key={iso}><Inspect title={tr(`${isotopeLabel[iso]} anchor model`)} value={evaluation.normalization[iso] ?? "Unavailable until verified anchors are measured"} /><div className="metro-actions">{evaluation.normalization[iso] && <button className="metro-btn" onClick={() => { const row = rows.find(r => r.isotopes?.[iso]); if (row) void inspect(`/evaluations/${evaluation.id}/monte-carlo?measurement_id=${row.id}&isotope=${iso}`, setEducational); }}>{tr("Monte Carlo check · ")}{tr(isotopeLabel[iso])}</button>}</div></div>)}{educational != null && <Inspect title={tr("Seeded Monte Carlo result")} value={educational} />}<Inspect title={tr("Per-analysis uncertainty budgets and issues")} value={evaluation.results} /></details>
        {run.context === "routine" && !locked && <div className="metro-actions"><button className="metro-btn primary" disabled={props.busy || !evaluation.ready || run.release_blockers.length > 0} onClick={() => void props.act(`/runs/${run.id}/release`, { evaluation_id: evaluation.id })}>{tr("Review and release results")}</button><span className="metro-muted">{tr("The reviewer and justification above are recorded permanently.")}</span></div>}
        {run.releases.map(r => <div className="metro-actions" key={r.id}><Status value="released" /><button className="metro-btn" disabled={props.busy} onClick={() => void props.act("/reports", { kind: "client", target_id: r.id })}>{tr("Generate client certificate")}</button></div>)}
      </> : <Empty>{tr("The file is preserved. An approved method is needed for normalized routine results.")}</Empty>}</div>}
    {tab === "traceability" && <><p className="metro-muted">{tr(run.source.isotope_basis)}. {tr(run.source.intensity_basis)}.</p><Inspect title={tr("Source hash, parser and column mapping")} value={run.source} /><Inspect title={tr("Run annotations and exclusions")} value={{ masses_ug: run.masses_ug, acquisition_complete: run.acquisition_complete, exclusions: run.exclusions, method_id: run.method_id }} />{evaluation && <Inspect title={tr("Immutable evaluation record")} value={evaluation} />}</>}
    {tr(localError && <p role="alert" className="metro-note error">{tr(localError)}</p>)}
  </Panel>;
}

function DiagnosticView({ data }: { data: Diagnostics }) {
  const tr = useTranslation();
  const [materialId, setMaterial] = useState(data.materials[0]?.material_id ?? "");
  const [iso, setIso] = useState<"d13c" | "d18o">("d13c");
  const [effect, setEffect] = useState("intensity_dependence");
  const material = data.materials.find(m => m.material_id === materialId) ?? data.materials[0];
  if (!material) return <Empty>{tr("No configured anchor or independent QC material was identified.")}</Empty>;
  const choices: Record<string, { label: string; x: string; fit: Fit }> = {
    intensity_dependence: { label: "Isotope vs intensity", x: "Sample I44 / V", fit: material.isotopes[iso].intensity_dependence },
    mass_dependence: { label: "Isotope vs mass", x: "Weighed mass / µg", fit: material.isotopes[iso].mass_dependence },
    drift: { label: "QC drift screening", x: "Analysis sequence", fit: material.isotopes[iso].drift },
    memory: { label: "QC memory screening", x: "Preceding isotope contrast / ‰", fit: material.isotopes[iso].memory },
    pressure_residual: { label: "Residual vs pressure adjustment", x: "Result minus target intensity / V", fit: material.isotopes[iso].pressure_residual },
    mass_to_co2_pressure: { label: "Mass vs CO₂ pressure", x: "Weighed mass / µg", fit: material.mass_to_co2_pressure },
    co2_pressure_to_i44: { label: "CO₂ pressure vs signal", x: "CO₂ sample pressure / µbar", fit: material.co2_pressure_to_i44 },
    mass_to_i44: { label: "Mass vs signal", x: "Weighed mass / µg", fit: material.mass_to_i44 },
  };
  const choice = choices[effect];
  return <div className="metro-stack"><div className="metro-note">{tr(data.note)}{tr(" Values shown here are the exported elemental means before application normalization. CO₂ pressure is retained as pressure, not converted to gas amount.")}</div><div className="metro-form-grid"><Field label={tr("Homogeneous material")}><select value={material.material_id} onChange={e => setMaterial(e.target.value)}>{data.materials.map(m => <option key={m.material_id} value={m.material_id}>{m.label} · {m.n}{tr(" aliquots")}</option>)}</select></Field><Field label={tr("Isotope")}><select value={iso} onChange={e => setIso(e.target.value as typeof iso)}>{isotopes.map(i => <option key={i} value={i}>{tr(isotopeLabel[i])}</option>)}</select></Field><Field label={tr("Diagnostic relationship")} wide><select value={effect} onChange={e => setEffect(e.target.value)}>{Object.entries(choices).map(([key, c]) => <option key={key} value={key}>{tr(c.label)}</option>)}</select></Field></div>
    {material.collinearity_warning && <div className="metro-note warn">{tr("Intensity and pressure mismatch are strongly correlated, r = ")}{tr(fmt(material.intensity_pressure_correlation))}{tr(". Two separate corrections may describe the same effect.")}</div>}
    <div className="metro-grid"><div><Scatter points={choice.fit.points ?? []} xLabel={tr(choice.x)} yLabel={tr(effect === "mass_to_co2_pressure" ? "CO₂ sample pressure / µbar" : ["mass_to_i44", "co2_pressure_to_i44"].includes(effect) ? "Sample I44 / V" : `${isotopeLabel[iso]} / ‰`)} /></div><dl><div className="metro-meter"><dt>{tr("Paired observations")}</dt><dd>{choice.fit.n}</dd></div><div className="metro-meter"><dt>{tr("Slope b")}</dt><dd>{tr(fmt(choice.fit.slope,6))}</dd></div><div className="metro-meter"><dt>{tr("Standard error u(b)")}</dt><dd>{tr(fmt(choice.fit.slope_se,6))}</dd></div><div className="metro-meter"><dt>{tr("Observed fitted span")}</dt><dd>{tr(fmt(choice.fit.effect_span))}</dd></div><div className="metro-meter"><dt>{tr("Residual standard error")}</dt><dd>{tr(fmt(choice.fit.residual_standard_error))}</dd></div><div className="metro-meter"><dt>{tr("R², descriptive only")}</dt><dd>{tr(fmt(choice.fit.r_squared))}</dd></div></dl></div>
    {!!material.isotopes[iso].repeatability_by_mass?.length && <section><h3>{tr("Repeatability by mass")}</h3><p className="metro-muted">{tr("Overall SD can include the deliberately varied mass effect. Pooled within-mass SD: ")}{tr(fmt(material.isotopes[iso].within_mass_pooled_sd))}‰.</p><div className="metro-table-wrap"><table><thead><tr><th>{tr("Mass / µg")}</th><th>{tr("Aliquots")}</th><th>{tr("Mean / ‰")}</th><th>{tr("SD / ‰")}</th><th>{tr("SE of mean / ‰")}</th></tr></thead><tbody>{material.isotopes[iso].repeatability_by_mass!.map(s => <tr key={s.mass_ug}><td>{tr(fmt(s.mass_ug,1))}</td><td>{s.n}</td><td>{tr(fmt(s.mean))}</td><td>{tr(fmt(s.sd))}</td><td>{tr(fmt(s.se_mean))}</td></tr>)}</tbody></table></div></section>}
    <p className="metro-muted">{tr(choice.fit.interpretation || "Slope, uncertainty of slope and uncertainty of an applied correction are different quantities. These diagnostics do not apply a correction.")}</p><Inspect title={tr("Fit residuals, covariance and confidence interval")} value={choice.fit} /><Inspect title={tr("All material diagnostics")} value={data} />
  </div>;
}
